services:
  bot:
    container_name: rss-bot
    build: .
    restart: always
    networks:
      - backend
    command: ["/rss-tg-bot", "-config", "/config/config.yaml"]
    volumes:
      - db_data:/data
      - ./config.yaml:/config/config.yaml:ro

networks:
  backend:

volumes:
  db_data:
