- name: install dependencies
  ansible.builtin.package:
    name:
      - git
      - make
    state: present

- name: ensure directories exists
  ansible.builtin.file:
    path: /opt/rss-tg-bot
    state: directory

- name: clone project
  ansible.builtin.git:
    dest: /opt/rss-tg-bot
    repo: "{{ rss_tg_bot_repo }}"
    version: "{{ rss_tg_bot_version }}"

- name: render config file
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: /opt/rss-tg-bot/config.yaml

- name: start bot service
  community.docker.docker_compose_v2:
    project_src: /opt/rss-tg-bot
    build: always
    remove_images: local
    services:
      - bot
